import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import pino from "pino";
import { describe, expect, it } from "vitest";
import { AgentManager } from "../../agent/agent-manager.js";
import { createGitHubService } from "../../../services/github-service.js";
import type { ForgeService } from "../../../services/forge-service.js";
import type { SessionOutboundMessage } from "../../messages.js";
import { createNoopWorkspaceGitService } from "../../test-utils/workspace-git-service-stub.js";
import { CheckoutSession } from "./checkout-session.js";
import {
  createAgentStructuredTextGeneration,
  createGitMetadataGenerator,
  type StructuredTextGeneration,
} from "./git-metadata-generator.js";

const FALLBACK_PR = {
  title: "Update changes",
  body: "Automated PR generated by woowtech smart.",
};

function metadataFixture() {
  const calls = {
    diff: 0,
    instructions: 0,
    repoRoot: 0,
    generation: 0,
    providers: 0,
    config: 0,
    selection: 0,
  };
  const workspaceGitService = createNoopWorkspaceGitService({
    getCheckoutDiff: async () => {
      calls.diff += 1;
      return { diff: "Synthetic private diff" };
    },
    resolveRepoRoot: async () => {
      calls.repoRoot += 1;
      throw new Error("Unexpected metadata filesystem access");
    },
  });
  const adapter = createAgentStructuredTextGeneration({
    agentManager: new AgentManager({
      logger: pino({ level: "silent" }),
      clients: {},
      providerDefinitions: {},
    }),
    providerSnapshotManager: {
      listProviders: async () => {
        calls.providers += 1;
        return [];
      },
    },
    readDaemonConfig: () => {
      calls.config += 1;
      return { metadataGeneration: { providers: [{ provider: "claude", model: "haiku" }] } };
    },
    getFocusedSelection: () => {
      calls.selection += 1;
      return undefined;
    },
  });
  const generation: StructuredTextGeneration = {
    generate: async (request) => {
      calls.generation += 1;
      return adapter.generate(request);
    },
  };
  const deps = {
    workspaceGitService,
    generation,
    buildMetadataPrompt: async () => {
      calls.instructions += 1;
      return "Synthetic metadata instructions";
    },
  };
  return { calls, deps };
}

function expectNoMetadataCalls(calls: ReturnType<typeof metadataFixture>["calls"]) {
  expect(calls).toEqual({
    diff: 0,
    instructions: 0,
    repoRoot: 0,
    generation: 0,
    providers: 0,
    config: 0,
    selection: 0,
  });
}

describe("woowtech git metadata OFF", () => {
  it("returns exact fixed text before diff, instructions, provider enumeration or generation", async () => {
    const f = metadataFixture();
    const generator = createGitMetadataGenerator(f.deps);
    expect(await generator.generateCommitMessage("/synthetic/private-repo")).toBe("Update files");
    expect(await generator.generatePullRequestText("/synthetic/private-repo", "main")).toEqual(
      FALLBACK_PR,
    );
    expectNoMetadataCalls(f.calls);
  });

  it("also blocks the production instructions builder before repository lookup", async () => {
    const f = metadataFixture();
    const generator = createGitMetadataGenerator({
      workspaceGitService: f.deps.workspaceGitService,
      generation: f.deps.generation,
    });
    expect(await generator.generateCommitMessage("/synthetic/private-repo")).toBe("Update files");
    expect(await generator.generatePullRequestText("/synthetic/private-repo")).toEqual(FALLBACK_PR);
    expectNoMetadataCalls(f.calls);
  });

  it("positive control: explicit test policy reaches the real provider resolver for both operations", async () => {
    const f = metadataFixture();
    const generator = createGitMetadataGenerator({ ...f.deps, isGenerationEnabled: () => true });
    expect(await generator.generateCommitMessage("/synthetic/private-repo")).toBe("Update files");
    expect(await generator.generatePullRequestText("/synthetic/private-repo", "main")).toEqual(
      FALLBACK_PR,
    );
    expect(f.calls).toEqual({
      diff: 2,
      instructions: 2,
      repoRoot: 0,
      generation: 2,
      providers: 2,
      config: 2,
      selection: 2,
    });
  });
});

function git(cwd: string, ...args: string[]): string {
  return execFileSync("git", args, {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();
}

// Only this temporary repository and its local bare remote are mutated. No daemon,
// provider executable, auth probe or external forge is started by this fixture.
function checkoutFixture() {
  const root = mkdtempSync(join(tmpdir(), "woowtech-git-metadata-"));
  const cwd = join(root, "checkout");
  const remote = join(root, "remote.git");
  mkdirSync(cwd);
  git(root, "init", "--bare", remote);
  git(cwd, "init", "-b", "main");
  git(cwd, "config", "user.name", "Metadata test");
  git(cwd, "config", "user.email", "metadata@example.invalid");
  git(cwd, "config", "commit.gpgsign", "false");
  git(cwd, "config", "core.hooksPath", join(root, "no-hooks"));
  writeFileSync(join(cwd, "file.txt"), "initial\n");
  git(cwd, "add", ".");
  git(cwd, "commit", "-m", "Initial");
  git(cwd, "remote", "add", "origin", remote);
  git(cwd, "push", "-u", "origin", "main");
  git(cwd, "checkout", "-b", "feature");
  const f = metadataFixture();
  const generated = { commit: 0, pr: 0 };
  const generator = createGitMetadataGenerator(f.deps);
  const requests: Array<Parameters<ForgeService["createPullRequest"]>[0]> = [];
  const emitted: SessionOutboundMessage[] = [];
  const mutations: string[] = [];
  const forge: ForgeService = {
    ...createGitHubService(),
    createPullRequest: async (request) => {
      requests.push(request);
      return { url: "https://example.invalid/pr/1", number: 1 };
    },
    invalidate: () => {},
  };
  const checkout = new CheckoutSession({
    host: {
      emit: (message) => {
        emitted.push(message);
      },
      emitWorkspaceUpdateForCwd: async () => {},
      handleWorkspaceGitBranchSnapshot: () => {},
      renameCurrentBranch: async () => {
        throw new Error("Unexpected rename");
      },
    },
    gitMutation: {
      notifyGitMutation: async (_cwd, reason) => {
        mutations.push(reason);
      },
      checkoutExistingBranch: async () => {
        throw new Error("Unexpected branch switch");
      },
    },
    workspaceGitService: createNoopWorkspaceGitService({
      ...f.deps.workspaceGitService,
      resolveForge: async () => ({ forge: "github", host: "example.invalid", service: forge }),
    }),
    github: forge,
    checkoutDiffManager: {
      read: async () => {
        throw new Error("Unexpected diff read");
      },
      subscribe: async () => {
        throw new Error("Unexpected diff subscription");
      },
      scheduleRefreshForCwd: () => {},
    },
    gitMetadataGenerator: {
      generateCommitMessage: async (path) => {
        generated.commit += 1;
        return generator.generateCommitMessage(path);
      },
      generatePullRequestText: async (path, base) => {
        generated.pr += 1;
        return generator.generatePullRequestText(path, base);
      },
    },
    paseoHome: join(root, "home"),
    worktreesRoot: undefined,
    logger: pino({ level: "silent" }),
  });
  return {
    ...f,
    cwd,
    checkout,
    generated,
    requests,
    emitted,
    mutations,
    cleanup: () => rmSync(root, { recursive: true, force: true }),
  };
}

describe("woowtech checkout handlers preserve user wording with metadata OFF", () => {
  it.each([undefined, " \n", "  My handwritten commit  "])(
    "commits with message %j",
    async (message) => {
      const f = checkoutFixture();
      try {
        writeFileSync(join(f.cwd, "file.txt"), "changed\n");
        await f.checkout.handleCheckoutCommitRequest({
          type: "checkout_commit_request",
          cwd: f.cwd,
          message,
          requestId: "commit",
        });
        expect(f.emitted).toMatchObject([
          { type: "checkout_commit_response", payload: { success: true, error: null } },
        ]);
        expect(git(f.cwd, "log", "-1", "--format=%B")).toBe(message?.trim() || "Update files");
        expect(f.generated.commit).toBe(message?.trim() ? 0 : 1);
        expect(f.mutations).toEqual(["commit-changes"]);
        expectNoMetadataCalls(f.calls);
      } finally {
        f.cleanup();
      }
    },
  );

  it.each([
    { title: undefined, body: undefined, expected: FALLBACK_PR, generated: 1 },
    { title: " \n", body: "\t", expected: FALLBACK_PR, generated: 1 },
    {
      title: "  Manual title  ",
      body: " Manual body\n",
      expected: { title: "Manual title", body: "Manual body" },
      generated: 0,
    },
    {
      title: "  Manual title  ",
      body: " ",
      expected: { ...FALLBACK_PR, title: "Manual title" },
      generated: 1,
    },
    {
      title: " ",
      body: " Manual body\n",
      expected: { ...FALLBACK_PR, body: "Manual body" },
      generated: 1,
    },
  ])("fills only blank PR fields: $title / $body", async ({ title, body, expected, generated }) => {
    const f = checkoutFixture();
    try {
      await f.checkout.handleCheckoutPrCreateRequest({
        type: "checkout_pr_create_request",
        cwd: f.cwd,
        title,
        body,
        baseRef: "main",
        requestId: "pr",
      });
      expect(f.emitted).toMatchObject([
        { type: "checkout_pr_create_response", payload: { number: 1, error: null } },
      ]);
      expect(f.requests).toEqual([{ cwd: f.cwd, ...expected, head: "feature", base: "main" }]);
      expect(f.generated.pr).toBe(generated);
      expect(f.mutations).toEqual(["create-pr"]);
      expectNoMetadataCalls(f.calls);
    } finally {
      f.cleanup();
    }
  });
});
