// Generates packages/app/src/i18n/resources/zh-TW.ts from upstream's Simplified
// Chinese translations (zh-CN.ts, plugin settings included): OpenCC's Simplified to
// Traditional conversion with Taiwan phrasing, then the fixes in zh-tw-terms.mjs.
// Upstream keeps zh-CN.ts current, so regenerating keeps Traditional Chinese current.
//
//   npm ci --prefix woowtech/tools                       # once
//   npx tsx woowtech/tools/generate-zh-tw.mjs            # write zh-TW.ts
//   npx tsx woowtech/tools/generate-zh-tw.mjs --check    # fail when zh-TW.ts is stale
//
// Re-run after any upstream merge that touches zh-CN.ts or plugin-settings.ts.
import { writeFileSync } from "node:fs";
import * as OpenCC from "opencc-js";

import { TERM_FIXES } from "./zh-tw-terms.mjs";

const resourcesDir = new URL("../../packages/app/src/i18n/resources/", import.meta.url);
const target = new URL("zh-TW.ts", resourcesDir);
const toTaiwanese = OpenCC.Converter({ from: "cn", to: "twp" });

function convertText(text, context) {
  let converted = toTaiwanese(text);
  for (const fix of TERM_FIXES) {
    if (fix.when && !fix.when(context)) continue;
    converted =
      typeof fix.find === "string"
        ? converted.replaceAll(fix.find, fix.replace)
        : converted.replace(fix.find, fix.replace);
  }
  return converted;
}

/** Converts every string, telling each fix the key path and the English source. */
function convert(value, english, path = []) {
  if (typeof value === "string") {
    return convertText(value, {
      key: path.join("."),
      english: typeof english === "string" ? english : "",
    });
  }
  if (Array.isArray(value)) {
    return value.map((child, index) => convert(child, english?.[index], [...path, index]));
  }
  if (typeof value === "object" && value !== null) {
    return Object.fromEntries(
      Object.entries(value).map(([key, child]) => [
        key,
        convert(child, english?.[key], [...path, key]),
      ]),
    );
  }
  return value;
}

function render(resources) {
  return [
    "// Generated by woowtech/tools/generate-zh-tw.mjs from zh-CN.ts. Do not edit by hand:",
    "// fix terms in woowtech/tools/zh-tw-terms.mjs and regenerate.",
    'import type { TranslationResources } from "./en";',
    "",
    `export const zhTW: TranslationResources = ${JSON.stringify(resources, null, 2)};`,
    "",
  ].join("\n");
}

const { zhCN } = await import(new URL("zh-CN.ts", resourcesDir).href);
const { en } = await import(new URL("en.ts", resourcesDir).href);
const zhTW = convert(zhCN, en);

if (process.argv.includes("--check")) {
  const { zhTW: committed } = await import(target.href);
  if (JSON.stringify(committed) !== JSON.stringify(zhTW)) {
    console.error("zh-TW.ts is out of date. Run: npx tsx woowtech/tools/generate-zh-tw.mjs");
    process.exit(1);
  }
  console.log("zh-TW.ts is up to date");
} else {
  writeFileSync(target, render(zhTW));
  console.log(`wrote ${target.pathname}`);
}
