// Vendored ACP provider SVG assets.

// woowtech smart: a vendor whose logo is not cleared shows its neutral text badge. Written
// by woowtech/tools/write-vendor-badges.mjs from woowtech/vendor-marks.mjs (README §22).
import { vendorBadgeSvg } from "../components/icons/vendor-badge";

export const ACP_PROVIDER_ICON_SVGS = {
  agy: vendorBadgeSvg("agy"),
  "agoragentic-acp": vendorBadgeSvg("agoragentic-acp"),
  "amp-acp": vendorBadgeSvg("amp-acp"),
  auggie: vendorBadgeSvg("auggie"),
  autohand: vendorBadgeSvg("autohand"),
  "claude-acp": vendorBadgeSvg("claude-acp"),
  cline: vendorBadgeSvg("cline"),
  "codebuddy-code": vendorBadgeSvg("codebuddy-code"),
  "codex-acp": vendorBadgeSvg("codex-acp"),
  "cortex-code": vendorBadgeSvg("cortex-code"),
  "corust-agent": vendorBadgeSvg("corust-agent"),
  "crow-cli": vendorBadgeSvg("crow-cli"),
  cursor: vendorBadgeSvg("cursor"),
  deepagents: vendorBadgeSvg("deepagents"),
  codewhale: vendorBadgeSvg("codewhale"),
  dimcode: vendorBadgeSvg("dimcode"),
  dirac: vendorBadgeSvg("dirac"),
  "factory-droid": vendorBadgeSvg("factory-droid"),
  "fast-agent": vendorBadgeSvg("fast-agent"),
  gemini: vendorBadgeSvg("gemini"),
  "github-copilot-cli": vendorBadgeSvg("github-copilot-cli"),
  gjc: vendorBadgeSvg("gjc"),
  "glm-acp-agent": vendorBadgeSvg("glm-acp-agent"),
  goose: vendorBadgeSvg("goose"),
  grok: vendorBadgeSvg("grok"),
  junie: vendorBadgeSvg("junie"),
  kilo: vendorBadgeSvg("kilo"),
  kimi: vendorBadgeSvg("kimi"),
  "minimax-code": vendorBadgeSvg("minimax-code"),
  "minion-code": vendorBadgeSvg("minion-code"),
  "mistral-vibe": vendorBadgeSvg("mistral-vibe"),
  nova: vendorBadgeSvg("nova"),
  opencode: vendorBadgeSvg("opencode"),
  poolside: vendorBadgeSvg("poolside"),
  qoder: vendorBadgeSvg("qoder"),
  "qwen-code": vendorBadgeSvg("qwen-code"),
  sigit: vendorBadgeSvg("sigit"),
  stakpak: vendorBadgeSvg("stakpak"),
  traecli: vendorBadgeSvg("traecli"),
  vtcode: vendorBadgeSvg("vtcode"),
} as const;
